### ISSUE TITLE
Invalid default configuration

### ISSUE THREAD

**Issue by michalbundyra** [mezzio/mezzio-authentication-oauth2#11]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | all ?

#### Summary

Default configuration provided is different than documented:

Configuration:
https://github.com/mezzio/mezzio-authentication-oauth2/blob/e4aa82b6a86dbf4bbc16eebce7d6aace61529cba/config/oauth2.php#L14-L15

Documentation:
https://github.com/mezzio/mezzio-authentication-oauth2/blob/master/docs/book/v1/intro.md#configuration

Generating keys:
https://github.com/mezzio/mezzio-authentication-oauth2/blob/e4aa82b6a86dbf4bbc16eebce7d6aace61529cba/bin/generate-oauth2-keys#L54

#### Current behavior

In the current configuration we have path set to `/data/public.key` and `/data/private.key` while documentation says default path is `/data/oauth/public.key` and `/data/oauth/private.key` and also generator put keys in that location.

I believe we have to update the configuration to set whatever is said in the documentation.

It can breaks some applications if someone relies on that "invalid" configuration.

**Comment by michalbundyra** [comment]
The same for encryption key:

https://github.com/mezzio/mezzio-authentication-oauth2/blob/e4aa82b6a86dbf4bbc16eebce7d6aace61529cba/config/oauth2.php#L41

**Comment by weierophinney** [comment]
I would go with the location where the key generator puts the keys, and make sure the documentation is indicating it correctly. Since the docs and key generator are in agreement, I'd consider the configuration to be incorrect here.
