### ISSUE TITLE
Failed to create private key

### ISSUE THREAD

**Issue by bumbleshet** [mezzio/mezzio-authentication-oauth2#13]
Hi, I tried to follow the installation steps in this link https://docs.mezzio.dev/mezzio-authentication-oauth2/v1/intro/ and tried running ./vendor/bin/generate-oauth2-keys. Afterward, I got the following logs:

```
This script is provided as a convenient way to generate keys for
the OAuth2 server provider. You may choose instead to use an
alternative method. For more information, see the install docs:
https://oauth2.thephpleague.com/installation/

Found a good location for keys:
<project path>\data

We'll put them in a subdirectory:
<project path>\data/oauth

Using 2048 bits to generate key of type RSA

Failed to create private key.
Check your openssl extension settings.
```
Am I missing something?

I already enabled the openssl extension in php.ini.

**Comment by geerteltink** [comment]
Without more info I'm afraid we can't do much. Are you sure the extension is loaded correctly?
Check this with ` php -r "echo OPENSSL_VERSION_TEXT;"`

Also checkout this page: https://www.php.net/manual/en/function.openssl-pkey-new.php
It says something about a valid openssl.cnf file.

**Comment by bumbleshet** [comment]
Closing this issue. Apparently, reinstalling Xampp in a newer version solves my problem.
