### ISSUE TITLE
Investigate test failure with league/oauth2-server 8.1.0

### ISSUE THREAD

**Issue by michalbundyra** [mezzio/mezzio-authentication-oauth2#14]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.0.2

#### Summary

[`league/oauth2-server` 8.1.0](https://github.com/thephpleague/oauth2-server/tree/8.1.0) has been released and we are getting one failure in our tests:

```
There was 1 failure:

1) MezzioTest\Authentication\OAuth2\Pdo\OAuth2PdoMiddlewareTest::testProcessClientCredentialGrant
Failed asserting that 401 matches expected 200.

/home/travis/build/mezzio/mezzio-authentication-oauth2/test/Pdo/OAuth2PdoMiddlewareTest.php:192
```

We need to investigate why this test is failing and fix it accordingly.
If the issue is with new release of oauth2-server we need create issue there and link it here.

**Comment by arueckauer** [comment]
This issue is solved and can be closed. Currently league/oauth2-server:8.2 is required.
