### ISSUE TITLE
Issues debugging

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication-oauth2#2]
### Code to reproduce the issue

this method blocks errors from being shown

```php
    public function authenticate(ServerRequestInterface $request) : ?UserInterface
    {
        try {
            $result = $this->resourceServer->validateAuthenticatedRequest($request);
            $userId = $result->getAttribute('oauth_user_id', false);
            if (false !== $userId) {
                return $this->generateUser($userId, []);
            }
        } catch (OAuthServerException $exception) {
            return null;
        }
        return null;
    }
```
and then if I fix it and add
```php
`throw $exception;`
```
into the catch, it runs...

```php
    public static function accessDenied($hint = null, $redirectUri = null)
    {
        return new static(
            'The resource owner or authorization server denied the request.',
```
which still hides the actual error message.

I don't see any way to access that $hint value. So currently I have no way to troubleshoot why I am getting totally blank results on API call tests.

I changed the static() return to pass $hint and the error causing this scenario was
```
The JWT string must have two dots
```
but it will be the same issue with any error

---

Originally posted by @pursehouse at https://github.com/zendframework/zend-expressive-authentication-oauth2/issues/39

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
