### ISSUE TITLE
persistNewAccessToken and persistNewRefreshToken

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication-oauth2#9]
- AccessTokenRepository : Lines 71 and 72
           ':revoked' => (int)false,
            ':expires_at' => date("Y-m-d H:i:s", $accessTokenEntity->getExpiryDateTime()->getTimestamp())
- RefreshTokenRepository : lines 32 and 33
$sth->bindValue(':revoked', (int)false);
        $sth->bindValue(':expires_at', date("Y-m-d H:i:s", $refreshTokenEntity->getExpiryDateTime()->getTimestamp()));

i have to make that, to persist the record without error.

Thanks.

---

Originally posted by @samiboukadida at https://github.com/zendframework/zend-expressive-authentication-oauth2/issues/8

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
